#!/usr/bin/env bash

# Change localhost to 127.0.0.2
sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts

# Map facebook.com to 8.8.8.8
if ! grep -q "facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
